index:
   path: /
   controller: App\Controller\HomeController::index

menu:
   path: /home
   controller: App\Controller\HomeController::menu
   methods: GET

add:
   path: /home/{id}
   controller: App\Controller\HomeController::add

indexPost:
   path: /home
   controller: App\Controller\HomeController::buttonPressed
   methods: POST
