index:
   path: /
   controller: App\Controller\HomeController::index

menu:
   path: /home
   controller: App\Controller\HomeController::menu
   methods: GET

order:
   path: /order
   controller: App\Controller\OrderController::index

add:
   path: /order/{id}
   controller: App\Controller\OrderController::add